[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['NPM_CONFIG_PRODUCTION=true npm install --omit=dev']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run server'

