[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run server"
healthcheckPath = "/health"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
ENCRYPTION_KEY = "AyAtO-LaUnChEr-2024-SeCrEt!!"

